### ISSUE TITLE
Button not reflecting current group

### ISSUE THREAD

**Issue by GollyJer** [char101/tabgroupsbtn#4]
Hi.  I'm using firefox 37 (not sure that matters or not) and the group tabGroupsButton:menu appears to have a bug.  It always displays the name of the last goup selected instead of the current group.  The toolbar shows things correctly.

If more info would help let me know.  I LOVE this simple piece of functionality.  Thanks!

**Comment by char101** [comment]
I have experienced this once but it was fixed after restarting the browser. Is this still happens after you restart the browser? What operating system do you use?

**Comment by jcelliott** [comment]
I'm having the same issue. I'm running Firefox 36 on Linux. It's been somewhat sporadic before, but now it happens consistently. I've restarted Firefox several times as well as disabling and re-enabling the extension. I would be happy to provide any information you need to resolve this.

**Comment by char101** [comment]
Fixed in 0.44

**Comment by jcelliott** [comment]
Awesome! Thanks.

**Comment by OdinGitDat** [comment]
This is still an issue for me, everytime I start up firefox the button just says "Tab Groups". I have to click it once for it to display the current group that I am in.

**Comment by char101** [comment]
That is by design. Loading panorama on Firefox startup is problematic.

**Comment by hidavy** [comment]
I suggest adding an option to display an icon on the button instead of label, and making the current group bold in the list. This makes it appear more consistent, compared with showing "Tab Groups" on startup. It saves some space as well.
Besides, I don't understand why not to implement sub-menus to display tabs, as "TabGroups Menu" does.
